# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None

# Run from backend/ directory; use cwd to locate app package
BASE_DIR = os.getcwd()

a = Analysis(
    ['run.py'],
    pathex=[BASE_DIR],
    binaries=[],
    datas=[
        ('../frontend/dist', 'frontend/dist'),
    ],
    hiddenimports=[
        'app',
        'app.api',
        'app.api.admin',
        'app.api.auth',
        'app.api.draw',
        'app.api.events',
        'app.api.payments',
        'app.api.pools',
        'app.api.setup',
        'app.api.upload',
        'app.api.warehouse',
        'app.database',
        'app.config',
        'app.dependencies',
        'app.models',
        'app.models.admin',
        'app.models.payment',
        'app.models.pool',
        'app.models.prize_grade',
        'app.models.ticket',
        'app.models.warehouse',
        'app.schemas',
        'app.schemas.admin',
        'app.schemas.payment',
        'app.schemas.pool',
        'app.schemas.setup',
        'app.schemas.ticket',
        'app.schemas.warehouse',
        'app.services',
        'app.services.auth',
        'app.services.events',
        'app.services.shuffle',
        'aiosqlite',
        'qrcode',
        'pyotp',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.middleware',
        'uvicorn.middleware.wsgi',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'PIL.ImageQt',
        'PIL.ImageShow',
        'PIL.TiffImagePlugin',
        'test',
        'unittest',
        'uvloop',
    ],
    noarchive=False,
    optimize=0,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='ichiban-server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    contents_directory='.',
)

# COLLECT creates a one-folder build
dist_dir = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='ichiban-server',
)
